[package]
name = "neofoodclub"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rand = "0.10.0"
bitflags = "2.11.0"
serde_qs = "0.15.0"
querystring = "1.1.0"
chrono = "0.4.43"
chrono-tz = "0.10.4"
comfy-table = "7.2.2"

[lib]
name = "neofoodclub"

[[example]]
name = "all_bets_table"
path = "examples/all_bets_table.rs"

[[bench]]
name = "math_benches"
harness = false

[dev-dependencies]
divan = { version = "4.3.0", package = "codspeed-divan-compat" }
